---
- hosts: all
  # become: yes

  vars_files:
      - vars.yml

  pre_tasks:
      - name: Update Homebrew
        community.general.homebrew:
          update_homebrew: yes
          upgrade_all: yes

  tasks:
  - name: Install brew formulae
    community.general.homebrew:
      name:
        - aspell
        - autoconf
        - automake
        - bash
        - bat
        - cloc
        - cmake
        - ctags
        - diff-so-fancy
        - dust
        - exa
        - fd
        - fzf
        - gawk
        - gcc
        - git
        - git-delta
        - git-extras
        - gnu-sed
        - gnupg
        - highlight
        - htop
        - hub
        - jq
        - mosh
        - most
        - nmap
        - nvm
        - perl
        - pinentry
        - psutils
        - pyenv
        - pyenv-virtualenv
        - rename
        - ripgrep
        - shellcheck
        - thefuck
        - tig
        - tree
        - watch
        - wget
        - youtube-dl
        - z
      state: present

  - name: Install brew casks
    community.general.homebrew_cask:
      name:
        - bettertouchtool
        - brave
        - calibre
        - contexts
        - drawio
        - flux
        - font-fira-code
        - font-hack-nerd-font
        - iina
        - insomnia
        - iterm2
        - java
        - julia
        - karabiner-elements
        - keepingyouawake
        - kindle
        - macdown
        - musescore
        - notion
        - staruml
        - suspicious-package
        - telegram
        - virtualbox
        - virtualbox-extension-pack
      state: present

  - name: Create dotfiles folder
    file:
      path: "{{ playbook_dir }}/dotfiles"
      state: directory

  - name: Prepare dotfiles
    template:
      src: "{{ item }}"
      dest: "{{ playbook_dir }}/dotfiles/{{ item | basename | regex_replace('\\.j2$', '') }}"
      owner: "{{ user_name }}"
      group: "{{ user_group }}"
    loop: "{{ lookup('fileglob', 'dotfiles_templates/*.j2', wantlist=True) }}"

  - name: Link dotfiles
    file:
      src: "{{ item }}"
      dest: "$HOME/.{{ item | basename }}"
      owner: "{{ user_name }}"
      group: "{{ user_group }}"
      state: link
    loop: "{{ lookup('fileglob', 'dotfiles/*', wantlist=True) }}"
