---
- hosts: all
  # become: yes

  vars_files:
      - vars.yml

  pre_tasks:
      - name: Update Homebrew
        community.general.homebrew:
          update_homebrew: yes
          upgrade_all: yes

  tasks:
    - import_tasks: tasks/brew.yml
    - import_tasks: tasks/shell.yml

  roles:
    - role: markosamuli.pyenv
      vars:
        pyenv_init_shell: false
        pyenv_global: "{{ pyenv_python38_version }} system"
