---
- name: Set zsh as default shell
  become: yes
  user:
    name: '{{ user_name }}'
    shell: /bin/zsh

- name: Install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "${ZDOTDIR:-$HOME}/.zprezto.bak"
    recursive: yes

- name: Link dotfiles
  template:
    src: "{{ item }}"
    dest: "$HOME/.{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
  loop: "{{ lookup('fileglob', 'dotfiles/*.j2', wantlist=True) }}"
